version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: typescript-node
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: joel
      MONGO_INITDB_ROOT_PASSWORD: secreto
