@url = http://localhost:3300/api/vuelos

### obtener todos los vuelos
GET {{url}}

### obtener un vuelo por id
GET {{url}}/2

### agregar un vuelo
POST {{url}}
Content-Type: application/json

{
  "date": "2023-12-11",
  "weather": "soleado",
  "visibility": "buena",
  "comment": "super wey"
}